CREATE TABLE [dbo].[TableSwapQueue] (
    [Id]                     INT         NOT NULL,
    [Name]                   NCHAR (200) NULL,
    [qty]                    TINYINT     DEFAULT ((0)) NOT NULL,
    [Price]                  NCHAR (10)  NULL,
    [PotSize]                NCHAR (10)  NULL,
    [Customer]               NCHAR (100) NULL,
    [Barcode]                NCHAR (13)  DEFAULT ((0.)) NULL,
    [Description]            NCHAR (500) NULL,
    [CommonName]             NCHAR (100) NULL,
    [PictureFile]            NCHAR (200) NULL,
    [ColourFont]             NCHAR (10)  NULL,
    [ColourFontColour]       NCHAR (10)  NULL,
    [FontBold]               BIT         DEFAULT ((0)) NOT NULL,
    [FontItalic]             BIT         DEFAULT ((0)) NOT NULL,
    [ColourBorderColour]     NCHAR (10)  NULL,
    [ColourBackgroundColour] NCHAR (10)  NULL,
    [notes]                  NCHAR (200) NULL,
    [Genus]                  NCHAR (100) NULL,
    [Species]                NCHAR (100) NULL,
    [Variety]                NCHAR (100) NULL,
    [AGM]                    BIT         DEFAULT ((0)) NOT NULL,
    [Picture1]               NCHAR (200) NULL,
    [Picture2]               NCHAR (200) NULL,
    [Picture3]               NCHAR (200) NULL,
    [Picture4]               NCHAR (200) NULL,
    [OrderNo.]               NCHAR (10)  NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);
